# Generated by Django 5.2.5 on 2025-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="is_published",
            new_name="published",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="preview_image",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
